# Generated by Django 5.0.3 on 2024-03-06 03:46

import custom_fk.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_fk.attr')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_fk.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='attrs',
            field=models.ManyToManyField(through='custom_fk.ProductAttr', to='custom_fk.attr'),
        ),
        migrations.CreateModel(
            name='UniqueProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom_fk.productattr')),
                ('product', custom_fk.models.CustomForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom_fk.product')),
            ],
        ),
    ]
